In [58]:
import pandas as pd

In [59]:
local_census_23 = pd.read_csv(r"C:\Users\EL081\Documents\project_1\golmok-sesac_project\data\raw\LOCAL_PEOPLE_DONG_202312.csv", encoding='utf-8',index_col=False)
local_census_24 = pd.read_csv(r"C:\Users\EL081\Documents\project_1\golmok-sesac_project\data\raw\LOCAL_PEOPLE_DONG_202412.csv", encoding='utf-8',index_col=False)
local_census_25 = pd.read_csv(r"C:\Users\EL081\Documents\project_1\golmok-sesac_project\data\raw\LOCAL_PEOPLE_DONG_202512.csv", encoding='utf-8',index_col=False)
area = pd.read_csv(r"C:\Users\EL081\Documents\project_1\golmok-sesac_project\data\raw\KIKcd_H.csv", encoding='utf-8')

In [60]:
dfs = {
    "local_23": local_census_23,
    "local_24": local_census_24,
    "local_25": local_census_25,
    "area": area
}

for name, df in dfs.items():
    print(f"{name}: {df['행정동코드'].dtype}")

local_23: int64
local_24: int64
local_25: int64
area: int64

In [61]:
local_census_25.head()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,남자45세부터49세생활인구수,남자50세부터54세생활인구수,남자55세부터59세생활인구수,남자60세부터64세생활인구수,남자65세부터69세생활인구수,남자70세이상생활인구수,여자0세부터9세생활인구수,여자10세부터14세생활인구수,여자15세부터19세생활인구수,여자20세부터24세생활인구수,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20251201,0,11740685,61486.3011,1715.3947,829.5068,1258.8852,1397.9777,2169.7450,2294.1596,2730.0607,2401.6276,2504.4365,2169.3634,2293.1626,1871.9333,1459.2393,3029.1803,1881.9202,860.1095,1298.7344,1750.0620,2899.6754,2601.8801,2753.0988,2354.0939,2521.4743,2525.8269,2555.4386,2329.3104,1991.6361,5038.3676
1,20251201,0,11740700,26294.6589,1233.6230,622.3062,716.9729,540.2120,777.1805,844.1471,1116.2297,966.3989,1064.5013,896.3260,960.6279,797.0339,577.8022,1213.9635,1119.5408,599.3389,565.5783,692.8982,975.0401,1004.7434,1069.4262,989.0583,1172.2281,915.0563,1159.7148,964.0480,708.1630,2032.4970
2,20251201,0,11740690,34999.7790,1776.0893,1346.0934,1017.6990,534.2654,567.4798,926.0529,1486.3564,1836.6503,1760.1008,1026.5642,1121.7082,856.0243,704.7631,1494.1557,1632.9647,1023.0644,676.9299,789.9825,753.4151,1109.7427,1846.5025,2059.5738,1638.9775,1150.7726,1334.6507,1170.8841,870.9271,2487.3885
3,20251201,0,11110515,14527.4001,583.5220,371.8216,479.6018,404.8372,410.6748,407.6887,464.0213,489.1421,661.6771,579.6267,474.0607,381.1812,205.7640,552.8469,659.5855,395.2050,472.1061,316.6720,399.9370,476.4736,685.2361,687.4558,767.6277,695.6938,603.6946,536.6778,328.9220,1035.6465
4,20251201,0,11110530,10739.6896,220.2106,97.8714,167.2910,233.1354,325.8158,389.4533,466.9244,506.2446,514.3574,532.9493,454.5065,331.2988,226.4337,455.2348,238.9307,127.9983,216.0011,392.2708,370.7485,412.4031,488.4795,499.1557,643.9031,522.5423,444.5721,400.0142,277.0544,783.8889

In [62]:
#3개년 데이터 합치기 위해 칼럼 같은지 확인
print(local_census_23.columns.equals(local_census_24.columns))
print(local_census_23.columns.equals(local_census_25.columns))

True
True

In [63]:
#3개년 데이터 합침

all_local_census = pd.concat(
    [local_census_23, local_census_24, local_census_25],
    axis=0,
    ignore_index=True
)

print(local_census_23.shape)
print(local_census_24.shape)
print(local_census_25.shape)
print(all_local_census.shape)

(315456, 32)
(315456, 32)
(315456, 32)
(946368, 32)

In [64]:
#결측치 확인

from IPython.display import display

display(all_local_census.isna().sum().to_frame("NaN count"))

                 NaN count
기준일ID                    0
시간대구분                    0
행정동코드                    0
총생활인구수                   0
남자0세부터9세생활인구수            0
남자10세부터14세생활인구수          0
남자15세부터19세생활인구수          0
남자20세부터24세생활인구수          0
남자25세부터29세생활인구수          0
남자30세부터34세생활인구수          0
남자35세부터39세생활인구수          0
남자40세부터44세생활인구수          0
남자45세부터49세생활인구수          0
남자50세부터54세생활인구수          0
남자55세부터59세생활인구수          0
남자60세부터64세생활인구수          0
남자65세부터69세생활인구수          0
남자70세이상생활인구수             0
여자0세부터9세생활인구수            0
여자10세부터14세생활인구수          0
여자15세부터19세생활인구수          0
여자20세부터24세생활인구수          0
여자25세부터29세생활인구수          0
여자30세부터34세생활인구수          0
여자35세부터39세생활인구수          0
여자40세부터44세생활인구수          0
여자45세부터49세생활인구수          0
여자50세부터54세생활인구수          0
여자55세부터59세생활인구수          0
여자60세부터64세생활인구수          0
여자65세부터69세생활인구수          0
여자70세이상생활인구수             0

In [65]:
area = area[area["시군구명"] == "마포구"]
area["행정동코드"] = area["행정동코드"] // 100
area

        행정동코드    시도명 시군구명   읍면동명      생성일자  말소일자
221  11440000  서울특별시  마포구    NaN  19880423   NaN
222  11440555  서울특별시  마포구    아현동  20080107   NaN
223  11440565  서울특별시  마포구    공덕동  20080107   NaN
224  11440585  서울특별시  마포구    도화동  20070101   NaN
225  11440590  서울특별시  마포구    용강동  19880423   NaN
226  11440600  서울특별시  마포구    대흥동  19880423   NaN
227  11440610  서울특별시  마포구    염리동  19880423   NaN
228  11440630  서울특별시  마포구    신수동  19880423   NaN
229  11440655  서울특별시  마포구    서강동  20070101   NaN
230  11440660  서울특별시  마포구    서교동  19880423   NaN
231  11440680  서울특별시  마포구    합정동  19880423   NaN
232  11440690  서울특별시  마포구  망원제1동  19880423   NaN
233  11440700  서울특별시  마포구  망원제2동  19880423   NaN
234  11440710  서울특별시  마포구    연남동  19880423   NaN
235  11440720  서울특별시  마포구  성산제1동  19880423   NaN
236  11440730  서울특별시  마포구  성산제2동  19880423   NaN
237  11440740  서울특별시  마포구    상암동  19880423   NaN

In [66]:
# '행정동코드' 칼럼을 기준으로 조인


all_local_census = all_local_census.merge(
    area[["행정동코드", "읍면동명"]],
    on="행정동코드",
    how="left"
)

all_local_census.head()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,남자45세부터49세생활인구수,남자50세부터54세생활인구수,남자55세부터59세생활인구수,남자60세부터64세생활인구수,남자65세부터69세생활인구수,남자70세이상생활인구수,여자0세부터9세생활인구수,여자10세부터14세생활인구수,여자15세부터19세생활인구수,여자20세부터24세생활인구수,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,읍면동명
0,20231201,0,11440700,17953.3267,614.2786,323.5466,356.4443,405.6338,579.7468,666.6332,847.2173,701.3165,833.5414,711.7532,586.7626,423.4003,272.8198,715.8886,439.6018,281.4152,446.8554,638.3925,844.6074,858.2800,991.7597,790.5823,847.5409,768.0834,713.8319,522.3086,461.9890,1309.0947,망원제2동
1,20231201,0,11530780,54855.2745,3449.0005,1359.3942,1208.6859,992.1033,1448.5719,1562.2772,2388.4425,2367.1088,2525.1911,1884.5997,1622.0724,1314.3903,941.4634,2196.5161,3548.0076,1398.5326,1518.7284,1431.5728,1751.8022,2031.0060,2749.7029,2306.7670,2300.0709,1977.0181,1943.2151,1766.8514,1281.0608,3591.1224,NaN
2,20231201,0,11410615,42154.9990,794.9889,522.7954,869.6627,2633.6971,2636.0144,1439.6448,1511.4632,1286.2844,1650.2968,1382.0657,1067.3933,944.1658,608.6949,1484.5825,1043.6003,633.5026,948.9488,3816.9569,2820.7278,1736.0611,1817.5186,1609.5025,1686.9845,1473.0774,1348.0668,1169.5408,829.1413,2389.6196,NaN
3,20231201,0,11530540,29693.1568,746.1579,308.1270,417.1508,838.5376,1958.1644,1942.4603,2076.1329,1647.0227,1713.1251,1291.6860,1090.9258,717.5379,445.4097,943.1326,658.1024,270.7816,308.1688,1145.9085,1680.3471,1457.5980,1463.1528,1047.2369,1149.5102,821.2493,910.8507,802.9093,558.5691,1283.2012,NaN
4,20231201,0,11740570,29622.1919,1255.9857,653.1830,704.1202,763.4152,932.8937,981.9935,1222.0471,1101.8459,1218.7777,1061.9023,1095.5892,926.9485,658.8662,1216.8486,972.2068,510.4089,637.6998,758.7806,950.9014,1163.9065,1347.9243,1147.0953,1456.6016,1221.4263,1373.3803,1152.1077,905.3051,2230.0321,NaN

In [68]:
all_local_census = all_local_census[all_local_census["읍면동명"].notna()]

all_local_census.head()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,남자45세부터49세생활인구수,남자50세부터54세생활인구수,남자55세부터59세생활인구수,남자60세부터64세생활인구수,남자65세부터69세생활인구수,남자70세이상생활인구수,여자0세부터9세생활인구수,여자10세부터14세생활인구수,여자15세부터19세생활인구수,여자20세부터24세생활인구수,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,읍면동명
0,20231201,0,11440700,17953.3267,614.2786,323.5466,356.4443,405.6338,579.7468,666.6332,847.2173,701.3165,833.5414,711.7532,586.7626,423.4003,272.8198,715.8886,439.6018,281.4152,446.8554,638.3925,844.6074,858.2800,991.7597,790.5823,847.5409,768.0834,713.8319,522.3086,461.9890,1309.0947,망원제2동
81,20231201,0,11440600,21836.0818,350.1405,246.7537,547.0457,1616.6843,1388.4981,858.6466,918.1070,793.2594,782.7988,648.4628,553.0828,356.8424,248.6518,595.3118,326.0011,184.8752,608.8283,2991.4625,1784.8230,1009.5911,886.2554,662.1512,737.8219,610.2046,462.8461,479.6404,314.0026,873.2923,대흥동
88,20231201,0,11440555,25861.9143,973.9217,306.2889,518.3661,427.2711,606.0322,907.7301,1355.0156,1241.3554,1177.9601,822.9768,821.2218,640.5269,462.0675,810.0918,2107.9551,587.2166,471.9550,710.6043,1032.8108,1285.8191,1715.6141,1264.9578,1141.3839,971.5194,877.9233,746.0125,560.6223,1316.6950,아현동
91,20231201,0,11440740,39326.5789,1755.1018,1083.1488,1187.7821,981.4700,1313.4928,1298.9289,1656.8471,1776.0227,2209.9097,1766.0600,1329.6683,933.1286,595.4718,1174.0629,1385.8727,888.5396,1362.7818,1368.3063,1765.4441,1484.3738,1840.9897,1730.9570,2127.5597,1305.9389,1185.2099,943.0629,835.9294,2040.5180,상암동
110,20231201,0,11440690,22983.4532,647.7159,319.0392,390.7694,693.9215,1033.9805,1129.7329,1286.4200,1014.6813,854.4381,703.5076,729.1599,486.9640,327.7057,796.0094,593.2231,311.8338,491.6163,904.3494,1347.3689,1255.6732,1409.9571,1094.7769,1023.3056,724.3658,773.4787,604.2210,506.8216,1528.4170,망원제1동